version: '3'
services:
  mongo:
    image: mongo:4
    ports:
      - 27017:27017

  api:
    image: node:12-alpine
    command: yarn start
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
      - "9229:9229"
