version: "3"
services:
  mongo:
    image: mongo:4
    ports:
      - 27017:27017

  pg:
    image: postgres:latest
    ports:
      - 9876:9876
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      PGPORT: 9876

  api:
    image: node:12-alpine
    command: yarn start
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
      - "9229:9229"
